### PR TITLE
Update probs prefix to w3id.org and version of rdflib 

### PR DESCRIPTION
**Pull request by stephenjboyle**
@ricklupton 

Hi Rick

I've made changes that are needed for building rdf files from md files in ```petrochemical-integrated-data``` using new w3id.org prefix.
Do you want me to bump ```src/sphinx_probs_rdf/version.py``` and update  ```CHANGELOG``` and if so what version number to use.
Also, do you want to keep as separate branch or merge into master. I think you will need to upload to twine.

Thanks

### CODE REVIEW

**Comment by ricklupton** [comment]
Hi @stephenjboyle I've added an example of how I'd update the changelog (can be done in the "unreleased" section independently of releasing a new version; when publishing a new version we just add a new heading for the new version making the unreleased section empty again). In this case it will be a breaking change so 0.4.x -> 0.5.0. I can do that after this is merged.

I took the opportunity to give a better prefix for the `PROBS_RECIPE` URIs. I don't think we have adapted any other code to use a new prefix here, so I think it's safe to choose this freely at this point (let me know if you think not).

Unless you see a problem with that change, please go ahead and merge this and tag me in the comment & I can release a new version. The other issue to increase compatibility with RDFox v6.2 can then be a bug fix as release 0.5.1.

**Comment by stephenjboyle** [comment]
@ricklupton 
Hi Rick, I've copied function preferredLabel from rdflib as mentioned in https://github.com/ricklupton/sphinx_probs_rdf/issues/4 
(did not see this earlier) and also modified ```setup.cfg``` to install at least rdflib 6.2.
I've tried using  petrochemical-integrated-data with rdflib 6.2 and tasks ```build_docs_rdf``` and ```enhance_data_unfccc``` run without errors when using icis object ```icis:SBR_\(Includes_SBCs\)```, so its seems to have fixed the problems we were having.
Is this ok to merge with master?

**Comment by ricklupton** [comment]
Thanks sounds good. One small comment above, and there should be a corresponding note added to the changelog that the required rdflib version had changed.

**Comment by stephenjboyle** [comment]
@ricklupton 
branch https://github.com/ricklupton/sphinx_probs_rdf/tree/new_probs_prefix merged into master.

**Comment by ricklupton** [comment]
Thanks @stephenjboyle. I've released version 0.5.0 including those changes.

**Pull request merged**
